<a href="https://colab.research.google.com/github/ANANAYAGG/AI_LAB/blob/main/DMA_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ARRAY CREATION**


In [7]:
arr = np.array([1, 2, 3])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

1
(3,)
3
int64


**indexing and slicing**

In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(arr[0, 1])
print(arr[0:2, 1:3])
print(arr.ndim)


[4 5 6]
[[[4 5 6]
  [7 8 9]]]
3


**BROADCASTING**

In [11]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print(a + b)


[[2 3 4]
 [3 4 5]
 [4 5 6]]


**ITERATION**

In [12]:
arr = np.array([[1, 2], [3, 4]])
for x in np.nditer(arr):
    print(x)


1
2
3
4


In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)


[5 7 9]
[ 4 10 18]


In [14]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))
print(np.std(arr))


3.0
1.4142135623730951


In [15]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))


[[19 22]
 [43 50]]


In [2]:
import numpy as np


records = [(1, 'Alice', 25.5), (2, 'Bob', 30.0), (3, 'Charlie', 28.0)]
dtype = [('id', 'i4'), ('name', 'U10'), ('age', 'f4')]


structured_array = np.rec.fromrecords(records, dtype=dtype)


print(structured_array['name'])

print(structured_array['age'])

['Alice' 'Bob' 'Charlie']
[25.5 30.  28. ]
